### ISSUE TITLE
orbital demo link to admin page is incorrect

### ISSUE THREAD

**Issue by ghost** [Orbitale/CmsBundle#13]
at
```
	http://www.orbitale.io/2015/12/28/cms-bundle.html
```
link
```
	View the demo here
	http://demo.orbitale.io/orbitale_cms/
```
follow to
```
	https://demo.orbitale.io/orbitale_cms/

	Homepage
		This page is set as homepage, but also as /{_locale}/homepage with a classic usage. Go to the admin page with the admin/admin user/password pair, and check the power of OrbitaleCmsBundle combined with EasyAdmin! 
```
link
```
	"the admin page"
	https://demo.orbitale.io/orbitale_cms/orbitale_cms/en/admin
```
is incorrect.

should be,
```
	https://demo.orbitale.io/orbitale_cms/en/admin
```

**Comment by Pierstoval** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by Pierstoval** [comment]
Thanks for the report, I fixed this issue in Orbitale/demos.orbitale_cms@796aef4 👍
