### ISSUE TITLE
Ethical question about how CmsBundle manage entities

### ISSUE THREAD

**Issue by aimproxy** [Orbitale/CmsBundle#23]
Hi again, u have called ur entity `Pages`, wich can be related to `Category`, but there aren't an entity `Posts`. I think `Pages` are pages, she should stay alone, and the entity `Posts` should be related to one or more `Category`! Finally, the url generated in `PostsController`, should look like this: `https://url.com/posts/year/month/day/subject`.

**Comment by Pierstoval** [comment]
Well, this is a "CmsBundle", not a "BlogBundle", so I don't see why we should rename the `Page` entity to `Post` or add a new entity for that :thinking: 

One could create a `Blog` category and put all blog posts in there as `Page` objects, and even use sub-categories as children of the `Blog` one if blog posts have to be categorized more precisely.

Something that could be interesting though is an inspiration of the `PageController` into the `PostController` you suggest, and changing the route would allow to inject the date in the URL instead of the full tree. It could still use the `Page` entity since a blog post is nothing more than a `Page` with a publish date, as the `createdAt` property is already here for that purpose :slightly_smiling_face: 

After all, these entities are abstract enough to be extended at will :wink: 

Feel free to contribute or make a PoC of such controller if you're interested, I'd be happy to help :)

**Comment by aimproxy** [comment]
I understand ur point of view, and I think inject the date in the url is a good idea in this conditions:

We should let users choose if they want to inject the date in the url, so this require a new field `Inject Datetime in URL`, and if is true, the url generated should look like this: `https://url_path/pages_path/category/year/month/day/title`. Did u agree with that?

I diden't find any useful tutorial about how to get started in creating bundles, I just don't know how to get start! Is there any command to setup this? Because the last time I submit the PR, it was harcoded in the vendor folder, and reloaded! kkk 👍

One more thing, u have a symfony deprication in `AbstractCmsController.php` line `16`, `Controller` is now deprecated should be `AbstractController`, right? I change this harcoded nothing happends, I'm guess its all fine!

**Comment by Pierstoval** [comment]
Such field would over-complexify the request handling. There's already a full parsing of the URL tree like `/parent/children/page` for page slugs and hierarchy.

As said, a single controller having a route like `/{year}/{month}/{day}/{slug}` would be enough and could still be overriden or customized or taken inspiration from :)

If you want to make a "proof of concept", feel free to create such controller in your app (it should be straightforward with the example given above), and if it is working for you, you can fork the bundle on Github, clone it on your machine and put the controller in it. You could create some functional tests for the controller, and if you don't know where to start, the best thing is to look at how the rest of the bundle is made :)

**Comment by Pierstoval** [comment]
> One more thing, u have a symfony deprication in `AbstractCmsController.php` line `16`, `Controller` is now deprecated should be `AbstractController`, right? I change this harcoded nothing happends, I'm guess its all fine!

I'm currently working on the 4.0 version of the bundle, and this deprecation will be removed.

I prefer to push things forward, deprecations are not a big deal, but to make the bundle compatible with Symfony 5.0 I'll make many other changes in the dependencies (mostly because of Doctrine).

I also wish to make it PHP 7.4 compatible, but for now the problem mostly comes from Behat/Transliterator, which I'll be able to remove for Symfony/String to remove deprecations too :)

**Comment by aimproxy** [comment]
Hi, it's me again, it worked like u said to do, I injected the `{year}/{month}/{day}/{slug}`.

The final result:
![route](https://user-images.githubusercontent.com/47716563/71475584-bddcba00-27d8-11ea-93dc-94039553cd6c.PNG)
![matched](https://user-images.githubusercontent.com/47716563/71475586-c03f1400-27d8-11ea-8047-a8a3f76c7445.PNG)

I will now produce the Tests, I have also some questions about PHPUnit!

**Comment by aimproxy** [comment]
So when I run PHPUnit, I received this error
`[Symfony\Component\ErrorHandler\Error\ClassNotFoundError]               
  Attempted to load class "TestCase" from namespace "PHPUnit\Framework".  
  Did you forget a "use" statement for another namespace?`

I allready google it, but I found nothing useful, seems the issue is in the `AbstractTestCase`!

**Comment by Pierstoval** [comment]
You should use PHPUnit 8.3 at least, but when using this package, the `vendor/bin/simple-phpunit` script should work as expected.

**Comment by aimproxy** [comment]
I'm reading the PHPUnit Documentation, and it's say it should be managed as a project-local dependency, but is not!

**Comment by Pierstoval** [comment]
It installed through the `symfony/phpunit-bridge`'s script in `vendor/bin/simple-phpunit` :)

**Comment by aimproxy** [comment]
How did I can setup this in PhpStorm

**Comment by Pierstoval** [comment]
Run `vendor/bin/simple-phpunit --version` in your terminal, this will install phpunit in `vendor/bin/.phpunit/....` directory and you can tell PHPStorm to use the `phpunit` script as if it was the PHAR file (there's an example there: https://www.orbitale.io/2019/11/16/setting-up-together-phpstorm-phpunit-xdebug-and-docker.html , it's using Docker but you don't have to use Docker with this bundle :) )

**Comment by aimproxy** [comment]
Thx for help, I setuped the PHPUnit successfully and now I have the following error: 
`[Symfony\Component\ErrorHandler\Error\FatalError]                                                                    
  Compile Error: Declaration of Orbitale\Bundle\CmsBundle\Tests\Fixtures\AbstractTestCase::setUp() must be compatible  
   with Symfony\Bundle\FrameworkBundle\Test\WebTestCase::setUp(): void` 

Can u help?

**Comment by Pierstoval** [comment]
Yep, you can checkout the `master` branch and try again, since I just merged #24 and it fixes many deprecations and issues :wink: If you do so, don't forget to run `composer update`!

**Comment by aimproxy** [comment]
Thx, I will check this tomorrow! 👍

**Comment by aimproxy** [comment]
Can I submit a PR without the tests, I don't have to much time to do it!?

**Comment by Pierstoval** [comment]
Reopening, since #25 is not merged yet 😉

**Comment by Pierstoval** [comment]
Merged 👍
